# Generated by Django 5.1.1 on 2025-01-27 07:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_client_website_alter_journalist_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("client", models.CharField(blank=True, max_length=250, null=True)),
                ("partner", models.CharField(blank=True, max_length=15, null=True)),
                ("country", models.CharField(blank=True, max_length=250, null=True)),
                ("additional_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
    ]
