# Generated by Django 5.1.1 on 2025-01-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_pressrelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressrelease",
            name="json_content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
