# Generated by Django 5.1.1 on 2025-01-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_pressrelease_json_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressrelease",
            name="client",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pressrelease",
            name="country",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pressrelease",
            name="partner",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pressrelease",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
