# Generated by Django 5.1.1 on 2025-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_pressrelease_client_alter_pressrelease_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressrelease",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_press_releases", to="core.journalist"
            ),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="status",
            field=models.CharField(default="draft", max_length=50),
        ),
    ]
