# Generated by Django 5.1.1 on 2025-02-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_pressrelease_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pressrelease",
            name="status",
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
