# Generated by Django 5.1.1 on 2025-02-28 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_pressrelease_status_pressrelease_is_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="location",
            new_name="country",
        ),
    ]
