# Generated by Django 5.1.1 on 2025-03-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_location_client_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients'),
        ),
    ]
